### ISSUE TITLE
2.1 As a non-admin user I want to be directed to the login page when I visit the site initially so that I can login or create a new account

### ISSUE THREAD

**Issue by pmcfarlain** [katebouis/GUI-DB#1]
Given a user is not logged in, when they are first entering the site, then they are directed to the login page
Given a user is logged in, when they are first entering the site, then they should be directed to their dashboard page (where NFT's for sale are shown, as well as NFT you are currently selling )

**Comment by pmcfarlain** [comment]
Just figured out how to do pull requests but I completed the user authentication. Everything needed from the backend should be completed now.

**Comment by AliceWonderland2019** [comment]
The login in is working with token
