### ISSUE TITLE
7.6 As a user, I want to view the total "worth" of NFT or NFT owners on the leaderboard so that I can know the exact worth of an NFT or the collective NFTs owned by a user

### ISSUE THREAD

**Issue by katebouis** [katebouis/GUI-DB#32]
Relative size: 3
Given that a user is visible on the NFT User leaderboard, then the total worth of all their NFTs should be visible next to their Username
Given that an NFT is on the NFT leaderboard, the price of the individual NFT should be visible next to the NFT name

**Comment by pmcfarlain** [comment]
Set up the logic to display this leaderboard in models/nft.js but haven't connected it with route or controller
