### ISSUE TITLE
3.8 As a purchaser I want to view money in my balance so I can see if I want to add money to my balance

### ISSUE THREAD

**Issue by j-kynerd** [katebouis/GUI-DB#48]
Size: 3

Given a user clicks view my money, when the click the button they can see the money on their account that can be used

Given the user has not added money, when they click view my money, a message appears that they have yet to add anything

**Comment by pmcfarlain** [comment]
A user's current balance can be viewed with the API call GET users/balance.
The backend is completed, waiting for frontend completion.

**Comment by AliceWonderland2019** [comment]
Change to balance will shows in profile
