### ISSUE TITLE
8.5 As an Administrator, I want to block a user from status on the leaderboard, so that those who disregard rules cannot attain a high status.

### ISSUE THREAD

**Issue by AliceWonderland2019** [katebouis/GUI-DB#8]

**Comment by pmcfarlain** [comment]
Combining this with 8.2. Creating a new permission level of 'Blocked' where users cannot interact with certain services or appear in the leaderboard.

**Comment by pmcfarlain** [comment]
The status is now set up, it just needs to be connected with the current message board/leaderboard routes
